name: contact_app_getx
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  alice: 0.4.1
  cached_network_image: null
  carousel_slider: null
  copy_with_extension: null
  crypto: ^3.0.3
  cupertino_icons: null
  curl_logger_dio_interceptor: null
  dartz: null
  device_info_plus: ^9.1.2
  dio: ^5.1.2
  dio_cache_interceptor: null
  dio_cache_interceptor_hive_store: null
  encrypt: null
  equatable: null
  file_picker: ^8.0.3
  flutter_dotenv: null
  flutter_form_builder: null
  flutter_svg: ^2.0.7
  form_builder_validators: null
  freezed_annotation: null
  flutter_html: 3.0.0-beta.2
  get: null
  hive: null
  sizer: 2.0.15
  hive_flutter: null
  image: ^4.1.7
  image_picker: null
  intl: null
  json_annotation: null
  lucide_icons: null
  open_filex: ^4.4.0
  package_info_plus: ^4.2.0
  path: ^1.8.0
  permission_handler: ^11.0.1
  pretty_dio_logger: null
  retrofit: null
  skeletonizer: null
  unicons: ^2.1.1
  url_launcher: ^6.0.20
  local_auth: ^2.3.0

dev_dependencies:
  build_runner: ^2.0.0

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  freezed: ^2.0.4
  husky: ^0.1.6
  json_serializable: ^6.3.1
  retrofit_generator: null
  mockito: ^5.0.8
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 100

  assets:
    # - assets/images/
    - assets/icons/
    - assets/fonts/
    - environments/
    # - shorebird.yaml
